# Tensorflow introduction

Import tensorflow

In [1]:
import tensorflow as tf

Creating tensors

In [2]:
string = tf.Variable('this is a string', tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

Rank/Degree of a tensor is the number of dimensiosns. The ones above are of rank 0, i.e., escalars

In [3]:
rank1_tensor = tf.Variable(["Test"], tf.string) #rank 1 (vector)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string) #rank 2 (matrix)

Determine the rank of a tensor

In [4]:
tf.rank(number) #rank 0 (escalar)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [5]:
tf.rank(rank1_tensor) #rank 1 (vector)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
tf.rank(rank2_tensor) #rank 2 (matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

Shape of a tensor

In [7]:
rank2_tensor.shape

TensorShape([2, 2])

Changing shape of a tensor

In [8]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor3 = tf.reshape(tensor2, [3, -1])

In [9]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


Types of tensosrs<br>
- Variable<br>
- Constant<br>
- Placeholder<br>
- SparseTensor<br>